- name: Update apt cache.
  when: ansible_os_family == 'Debian'
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 600

- name: "Install debian dependencies"
  when: ansible_os_family == 'Debian'
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ acme_debian_dependencies }}"

- name: Ensure acme clone directory exists
  become: true
  ansible.builtin.file:
    path: "{{ acme_git_clone_dest | dirname }}"
    state: "directory"
    mode: "0755"

- name: Clone acme repo
  become: true
  ansible.builtin.git:
    repo: "{{ acme_git_url }}"
    version: "{{ acme_git_version }}"
    dest: "{{ acme_git_clone_dest }}"
    update: "{{ acme_git_update }}"

- name: Install acme.sh
  become: true
  ansible.builtin.command: >-
    ./acme.sh --install
    {{ "-m " + acme_account_email if acme_account_email else "" }}
  args:
    chdir: "{{ acme_git_clone_dest }}"
    creates: "~/.acme.sh/acme.sh"

- name: Upgrade acme.sh
  become: true
  when: acme_upgrade
  ansible.builtin.command: ./acme.sh --upgrade
  args:
    chdir: "~/.acme.sh"
  register: acme_upgrade_result
  changed_when: >-
    acme_upgrade_result.rc == 0 and
    "Upgrade success" in upgrade_result.stdout
