- name: Set wanted domains for removal
  ansible.builtin.set_fact:
    acme_wanted_domains: "{{ acme_cert_domains | map(attribute='domains') | map('first') | list }}"
  when: acme_cert_domains is defined

- name: Get all active certs
  ansible.builtin.shell: |
    set -o pipefail
    ~/.acme.sh/acme.sh --list | tail -n +2 | awk -F ' ' '{print $1}'
  args:
    executable: /bin/bash
  register: acme_list_output
  changed_when: false

- name: Set domains to remove
  ansible.builtin.set_fact:
    acme_domains_to_remove: >-
      {{
        (acme_list_output.stdout_lines | default([]))
        | reject('in', acme_wanted_domains | default([]))
        | list
      }}
  when: acme_list_output.stdout_lines is defined and acme_list_output.stdout_lines | length > 0

- name: Remove all unwanted certs
  ansible.builtin.include_tasks: remove_single_cert.yml
  loop: "{{ acme_domains_to_remove }}"
  loop_control:
    loop_var: domain
  when: acme_domains_to_remove is defined and acme_domains_to_remove | length > 0
